import {
  CHAPTER_OPTIMIZE_DRAFT_SYSTEM_PROMPT,
  CHAPTER_OPTIMIZE_DRAFT_TEMPLATE_KEY,
  CHAPTER_OPTIMIZE_PLAN_SYSTEM_PROMPT,
  CHAPTER_OPTIMIZE_PLAN_TEMPLATE_KEY,
  CHAPTER_OPTIMIZE_TYPO_CHECK_SYSTEM_PROMPT,
  CHAPTER_OPTIMIZE_TYPO_CHECK_TEMPLATE_KEY,
  CHAPTER_OPTIMIZE_TYPO_FIX_SYSTEM_PROMPT,
  CHAPTER_OPTIMIZE_TYPO_FIX_TEMPLATE_KEY,
} from '../projects/chapter-optimize.util';
import {
  CHAPTER_COMPLIANCE_OUTLINE_SYSTEM_PROMPT,
  CHAPTER_COMPLIANCE_OUTLINE_TEMPLATE_KEY,
  CHAPTER_COMPLIANCE_REWRITE_SYSTEM_PROMPT,
  CHAPTER_COMPLIANCE_REWRITE_TEMPLATE_KEY,
  CHAPTER_COMPLIANCE_COVERAGE_VERIFY_TEMPLATE_KEY,
  CHAPTER_COMPLIANCE_REWRITE_FIX_ITEMS_TEMPLATE_KEY,
} from '../projects/compliance-check.util';
import {
  CHAPTER_PIPELINE_CHARACTER_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_CHARACTER_TEMPLATE_KEY,
  CHAPTER_PIPELINE_CHARACTER_OUTLINE_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_CHARACTER_OUTLINE_TEMPLATE_KEY,
  CHAPTER_PIPELINE_CHARACTER_TRAITS_OUTLINE_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_CHARACTER_TRAITS_OUTLINE_TEMPLATE_KEY,
  CHAPTER_PIPELINE_CHARACTER_TRAITS_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_CHARACTER_TRAITS_TEMPLATE_KEY,
  CHAPTER_PIPELINE_HOMOGENIZATION_REWRITE_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_HOMOGENIZATION_REWRITE_TEMPLATE_KEY,
  CHAPTER_PIPELINE_HOMOGENIZATION_SCAN_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_HOMOGENIZATION_SCAN_TEMPLATE_KEY,
  CHAPTER_PIPELINE_RULES_FIX_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_RULES_FIX_TEMPLATE_KEY,
  CHAPTER_PIPELINE_RULES_SCAN_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_RULES_SCAN_TEMPLATE_KEY,
  CHAPTER_PIPELINE_SENSORY_OUTLINE_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_SENSORY_OUTLINE_TEMPLATE_KEY,
  CHAPTER_PIPELINE_SENSORY_REWRITE_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_SENSORY_REWRITE_TEMPLATE_KEY,
  CHAPTER_PIPELINE_SENSORY_REWRITE_REVISE_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_SENSORY_REWRITE_REVISE_TEMPLATE_KEY,
  CHAPTER_PIPELINE_OUTLINE_COVERAGE_VERIFY_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_REWRITE_FIX_ITEMS_SYSTEM_PROMPT,
  CHAPTER_PIPELINE_CHARACTER_COVERAGE_VERIFY_TEMPLATE_KEY,
  CHAPTER_PIPELINE_CHARACTER_TRAITS_COVERAGE_VERIFY_TEMPLATE_KEY,
  CHAPTER_PIPELINE_SENSORY_COVERAGE_VERIFY_TEMPLATE_KEY,
  CHAPTER_PIPELINE_CHARACTER_REWRITE_FIX_ITEMS_TEMPLATE_KEY,
  CHAPTER_PIPELINE_CHARACTER_TRAITS_REWRITE_FIX_ITEMS_TEMPLATE_KEY,
  CHAPTER_PIPELINE_SENSORY_REWRITE_FIX_ITEMS_TEMPLATE_KEY,
} from '../projects/chapter-pipeline.util';

export interface TaskPromptDefinition {
  templateKey: string;
  name: string;
  defaultText: string;
}

/** 首期 task prompt 白名单（与需求 AQ-250 一致） */
export const TASK_PROMPT_DEFINITIONS: TaskPromptDefinition[] = [
  {
    templateKey: CHAPTER_OPTIMIZE_PLAN_TEMPLATE_KEY,
    name: '章节优化 · 方案',
    defaultText: CHAPTER_OPTIMIZE_PLAN_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_OPTIMIZE_DRAFT_TEMPLATE_KEY,
    name: '章节优化 · 正文',
    defaultText: CHAPTER_OPTIMIZE_DRAFT_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_OPTIMIZE_TYPO_CHECK_TEMPLATE_KEY,
    name: '章节优化 · 错字检查',
    defaultText: CHAPTER_OPTIMIZE_TYPO_CHECK_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_OPTIMIZE_TYPO_FIX_TEMPLATE_KEY,
    name: '章节优化 · 错字修正',
    defaultText: CHAPTER_OPTIMIZE_TYPO_FIX_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_COMPLIANCE_OUTLINE_TEMPLATE_KEY,
    name: '终稿合规 · 大纲',
    defaultText: CHAPTER_COMPLIANCE_OUTLINE_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_COMPLIANCE_REWRITE_TEMPLATE_KEY,
    name: '终稿合规 · 改写',
    defaultText: CHAPTER_COMPLIANCE_REWRITE_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_CHARACTER_OUTLINE_TEMPLATE_KEY,
    name: '分步精修 · 角色调整大纲',
    defaultText: CHAPTER_PIPELINE_CHARACTER_OUTLINE_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_CHARACTER_TEMPLATE_KEY,
    name: '分步精修 · 角色调整',
    defaultText: CHAPTER_PIPELINE_CHARACTER_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_CHARACTER_TRAITS_OUTLINE_TEMPLATE_KEY,
    name: '分步精修 · 角色特征润色大纲',
    defaultText: CHAPTER_PIPELINE_CHARACTER_TRAITS_OUTLINE_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_CHARACTER_TRAITS_TEMPLATE_KEY,
    name: '分步精修 · 角色特征润色',
    defaultText: CHAPTER_PIPELINE_CHARACTER_TRAITS_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_SENSORY_OUTLINE_TEMPLATE_KEY,
    name: '分步精修 · 感官大纲',
    defaultText: CHAPTER_PIPELINE_SENSORY_OUTLINE_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_SENSORY_REWRITE_TEMPLATE_KEY,
    name: '分步精修 · 感官改写',
    defaultText: CHAPTER_PIPELINE_SENSORY_REWRITE_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_SENSORY_REWRITE_REVISE_TEMPLATE_KEY,
    name: '分步精修 · 感官改写按意见再改',
    defaultText: CHAPTER_PIPELINE_SENSORY_REWRITE_REVISE_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_CHARACTER_COVERAGE_VERIFY_TEMPLATE_KEY,
    name: '分步精修 · 角色调整落实验收',
    defaultText: CHAPTER_PIPELINE_OUTLINE_COVERAGE_VERIFY_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_CHARACTER_TRAITS_COVERAGE_VERIFY_TEMPLATE_KEY,
    name: '分步精修 · 特征润色落实验收',
    defaultText: CHAPTER_PIPELINE_OUTLINE_COVERAGE_VERIFY_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_SENSORY_COVERAGE_VERIFY_TEMPLATE_KEY,
    name: '分步精修 · 感官改写落实验收',
    defaultText: CHAPTER_PIPELINE_OUTLINE_COVERAGE_VERIFY_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_CHARACTER_REWRITE_FIX_ITEMS_TEMPLATE_KEY,
    name: '分步精修 · 角色调整按项补修',
    defaultText: CHAPTER_PIPELINE_REWRITE_FIX_ITEMS_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_CHARACTER_TRAITS_REWRITE_FIX_ITEMS_TEMPLATE_KEY,
    name: '分步精修 · 特征润色按项补修',
    defaultText: CHAPTER_PIPELINE_REWRITE_FIX_ITEMS_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_SENSORY_REWRITE_FIX_ITEMS_TEMPLATE_KEY,
    name: '分步精修 · 感官改写按项补修',
    defaultText: CHAPTER_PIPELINE_REWRITE_FIX_ITEMS_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_COMPLIANCE_COVERAGE_VERIFY_TEMPLATE_KEY,
    name: '终稿合规 · 落实验收',
    defaultText: CHAPTER_PIPELINE_OUTLINE_COVERAGE_VERIFY_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_COMPLIANCE_REWRITE_FIX_ITEMS_TEMPLATE_KEY,
    name: '终稿合规 · 按项补修',
    defaultText: CHAPTER_PIPELINE_REWRITE_FIX_ITEMS_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_RULES_SCAN_TEMPLATE_KEY,
    name: '分步精修 · 规则扫描',
    defaultText: CHAPTER_PIPELINE_RULES_SCAN_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_RULES_FIX_TEMPLATE_KEY,
    name: '分步精修 · 规则修复',
    defaultText: CHAPTER_PIPELINE_RULES_FIX_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_HOMOGENIZATION_SCAN_TEMPLATE_KEY,
    name: '分步精修 · 同质化检测',
    defaultText: CHAPTER_PIPELINE_HOMOGENIZATION_SCAN_SYSTEM_PROMPT,
  },
  {
    templateKey: CHAPTER_PIPELINE_HOMOGENIZATION_REWRITE_TEMPLATE_KEY,
    name: '分步精修 · 同质化改写',
    defaultText: CHAPTER_PIPELINE_HOMOGENIZATION_REWRITE_SYSTEM_PROMPT,
  },
];

const DEFINITION_BY_KEY = new Map(
  TASK_PROMPT_DEFINITIONS.map((item) => [item.templateKey, item] as const)
);

export function isAllowedTaskPromptKey(templateKey: string): boolean {
  return DEFINITION_BY_KEY.has(templateKey.trim());
}

export function getTaskPromptDefinition(templateKey: string): TaskPromptDefinition {
  const key = templateKey.trim();
  const def = DEFINITION_BY_KEY.get(key);
  if (!def) {
    throw new Error(`不支持的 task prompt templateKey: ${templateKey}`);
  }
  return def;
}

export function getWarehouseDefaultTaskPromptText(templateKey: string): string {
  return getTaskPromptDefinition(templateKey).defaultText;
}
